apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::628936956560:role/eksctl-UdacityDev-EKS-Cluster-nod-NodeInstanceRole-R1AUVR3GQ9GT
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes