--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: UdacityDev-EKS-Cluster
  region: ap-southeast-2

vpc:
  id: "vpc-0af1340910bcbd013"  # (optional, must match VPC ID used for each subnet below)
  cidr: "10.16.0.0/16"       # (optional, must match CIDR used by the given VPC)
  subnets:
    # must provide 'private' and/or 'public' subnets by availibility zone as shown
    public:
      ap-southeast-2a:
        id: "subnet-045085aff0f47213a"
        cidr: "10.16.10.0/24"
      ap-southeast-2b:
        id: "subnet-0cc0baef81cbe15a3"
        cidr: "10.16.11.0/24"
    private:
      ap-southeast-2a:
        id: "subnet-019ac66c45aa12345"
        cidr: "10.16.20.0/24" # (optional, must match CIDR used by the given subnet)

      ap-southeast-2b:
        id: "subnet-0fb0cc3700482c87b"
        cidr: "10.16.21.0/24"  # (optional, must match CIDR used by the given subnet)

nodeGroups:
  - name: ng-1
    instanceType: t3.large
    desiredCapacity: 2
    volumeSize: 80
    ssh: 
      publicKeyName: jenkins
