Description: This is the template that will deploy Jenkins Instance (Ubuntu) with the jenkins installed
Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String

Resources:
  JenkinsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Allow http and ssh on bastion instance'
      SecurityGroupIngress:
        - CidrIp: '0.0.0.0/0'
          IpProtocol: 'tcp'
          FromPort: 80
          ToPort: 80
        - CidrIp: '0.0.0.0/0'
          IpProtocol: 'tcp'
          FromPort: 22
          ToPort: 22
        - CidrIp: '0.0.0.0/0'
          IpProtocol: 'tcp'
          FromPort: 8080
          ToPort: 8080
      VpcId:
        Fn::ImportValue: !Sub '${EnvironmentName}-VPC'

  JenkinsInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0987943c813a8426b
      InstanceType: t2.micro
      KeyName: 'jenkins'
      SecurityGroupIds:
        - Ref: JenkinsSecurityGroup
      SubnetId:
        Fn::ImportValue: !Sub ${EnvironmentName}-PublicSubnet1
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo su
          apt update
          apt install -y openjdk-8-jre
          wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -
          sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
          apt update
          apt install jenkins -y
          systemctl start jenkins
          ufw allow 8080/tcp
          apt install unzip
          apt install glibc-source
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install